#!/bin/bash

set -x

hdmi_status=$(cat /sys/class/drm/card0-HDMI-A-1/status)

if [[ $hdmi_status == "connected" ]]; then
	/home/rob/bash_scripts/hdmi_sound_on
else
	/home/rob/bash_scripts/hdmi_sound_off	
fi

alsactl restore